name: Test api

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "**/requirements*.txt"

      - name: Install dependencies
        working-directory: ./api
        run: |
          pip install ".[dev]" -r requirements.txt -r requirements_dev.txt

      - name: pytest
        working-directory: ./api
        run: pytest
